version: '3.7'
services:
  rpx:
    build:
      context: nginx/
    labels:
        co.elastic.logs/module: "nginx"
        co.elastic.logs/fileset.stdout: "access"
        co.elastic.logs/fileset.stderr: "error"
    volumes: 
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./ssl
        target: /etc/ssl
        read_only: true
    networks:
      - byappt
    ports:
      - "80:80"
      - "443:443"

networks:
  rev-pxy:
  jenkins:
    external: true
    
